# Generated by Django 3.2.5 on 2021-08-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='catagory',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
