# Generated by Django 3.2.5 on 2021-08-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mini_title',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
