# Generated by Django 3.2.5 on 2021-08-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
