# Generated by Django 3.2.5 on 2021-09-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
