# Generated by Django 3.2.5 on 2021-09-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_alter_catagory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='catagory',
            new_name='catagory_name',
        ),
    ]
