# Generated by Django 3.2.5 on 2021-09-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0012_rename_catagory_catagory_catagory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField()),
                ('profile_pic', models.ImageField(default='images\\profile_pic\\default-avatar.jpg', upload_to='images/profile_pic/')),
            ],
        ),
    ]
