# Generated by Django 3.2.5 on 2021-09-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0016_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('Female', 'female'), ('others', 'Others')], max_length=20),
        ),
    ]
