# Generated by Django 3.2.5 on 2021-09-03 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0017_alter_users_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='like_Post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liked_on', to='Post.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likes',
            name='liked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[('others', 'Others'), ('male', 'male'), ('Female', 'female')], max_length=20),
        ),
    ]
