# Generated by Django 3.2.5 on 2021-09-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0022_auto_20210911_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[('others', 'Others'), ('male', 'male'), ('Female', 'female')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(default='profile_pic\\default-avatar.jpg', upload_to='profile_pic/'),
        ),
    ]
