# Generated by Django 3.2.5 on 2021-09-12 07:03

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0023_auto_20210911_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/catagory/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('Female', 'female'), ('others', 'Others')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(default='profile_pic\\default-avatar.jpg', upload_to=Post.models.rename),
        ),
    ]
