# Generated by Django 3.2.5 on 2021-09-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0024_auto_20210912_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catagory/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('others', 'Others'), ('Female', 'female')], default=None, max_length=20, null=True),
        ),
    ]
